spring:
  application:
    name: sportify
  cloud:
    aws:
      secretsmanager:
        enabled: true
      region:
        static: us-east-1
  jwt:
    secret-name: jwt-secret
  auth:
    white-list:  /users/register, /users/login, /swagger-resources/**, /swagger-ui.html, /v2/api-docs, /webjars/**, /swagger-ui/**
  datasource:
    url: jdbc:mysql://localhost:3306/sportify
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
server: # URL -> http://localhost:8080/swagger-ui/
  forward-headers-strategy: framework
